### ISSUE TITLE
Compatible with Keycloak 22 (JAX-RS)? 

### ISSUE THREAD

**Issue by anothergoodguy** [daniel-frak/keycloak-user-migration#127]
Hi,

Context and dependency injection no longer enabled to JAX-RS Resources

Source: https://www.keycloak.org/2023/07/keycloak-2200-released

Do you plan to support keycloak 22 ?

**Comment by daniel-frak** [comment]
Is the context and dependency injection removal an issue in the context of updating the plugin?

Otherwise, I don't see a problem in updating the dependencies (and maybe fixing some deprecations). I'm just not sure when I'll have the time to get around to it.

I do encourage you to create a Pull Request for it if it's something you need done fast :)

**Comment by pschichtel** [comment]
I have the plugin running in a keycloak 22 instance without issues. looking at the code it doesn't seem there's any changes needed since 21.

**Comment by juniorbertolini** [comment]
In keycloak 22, the users list on admin console is not working for me (the integration apparently workfine). Do you mind to share with me how you managed to fix this @pschichtel?

**Comment by patrickmichalina** [comment]
@juniorbertolini @pschichtel any updates on this @daniel-frak. v22 of keycloak the admin UI is not showing users for us as well.

**Comment by pschichtel** [comment]
I haven't touched the plugin, I built it and I deployed it. Can you elaborate on what exactly isn't working in the usee list and how that can be observed?

**Comment by patrickmichalina** [comment]
I shouldn't have tagged you in the previous message. The behavior is that the default query when you navigate to the "users" page results in an empty list (nothing on the page). However, if you perform a search using the input field, it will then display users as normal. It seems to only break the default page route, but detailed user view and username search still work.

**Comment by pschichtel** [comment]
Ah, I noticed that myself, but already quite a few keycloak versions ago. I actually thought this was a change in keycloak.

**Comment by alishchytovych** [comment]
Confirm the issue with the list of users, and the issue with keycloak-orgs extension - users created via org IdP are not automatically joined to the org. Kindly ask to fix.

**Comment by DanielFrak** [comment]
I'll try to carve out some time soon to update the dependencies of the plugin.
Hopefully that will fix any issues with Keycloak 22.

**Comment by daniel-frak** [comment]
I'll try to carve out some time soon to update the dependencies of the plugin.
Hopefully that will fix any issues with Keycloak 22.

**Comment by daniel-frak** [comment]
I have updated the dependencies to support Keycloak 22 and updated the E2E tests so that they all pass.
Everything should work correctly now (as evidenced by the passing tests). As such, I'm closing this issue.

Version [2.0.0](https://github.com/daniel-frak/keycloak-user-migration/releases/tag/2.0.0) of the plugin is the one you want to use with Keycloak 22.

If any other problems persist, please open a new issue, following the [guidelines](https://github.com/daniel-frak/keycloak-user-migration/blob/91ab28075bdb6964b1abc3489c2a80a335ece472/CONTRIBUTING.md#write-bug-reports-with-detail-background-and-sample-code).
