### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by ralphsaunders** [daniel-frak/keycloak-user-migration#193]
Hi Daniel,

Thank you for putting in the effort with this provider, it looks really useful.

I was reviewing the documentation and I had a question about the design of the provider.

The docs mention the legacy system needs to provide endpoints for verifying user credentials and providing user info. It occurred to me that OIDC protocol provides those endpoints. Credentials could be verified with ROPC (password grant) and user info could probably be gathered from the `/userinfo` endpoint.

In an OIDC -> OIDC system migration, could you foresee any issues with the above design approach? My thinking was this would eliminate the need for any bespoke services to be developed for a legacy system if it had OIDC support.

Thank you kindly,
Ralph

**Comment by daniel-frak** [comment]
I imagine it should be possible, depending on the legacy OIDC system configuration - after all, all my plugin really does it pass the username and password along, then retrieve user details.

One thing is for sure, though - it won't work out of the box with this plugin, because the endpoints are bespoke.

I'd suggest you look at the [LegacyProvider](https://github.com/daniel-frak/keycloak-user-migration/blob/master/src/main/java/com/danielfrak/code/keycloak/providers/rest/LegacyProvider.java) code and see if you can easily translate it to communicate with another OIDC provider.

It might turn out that you will only need to modify the [RestUserService](https://github.com/daniel-frak/keycloak-user-migration/blob/master/src/main/java/com/danielfrak/code/keycloak/providers/rest/rest/RestUserService.java) to speak to the OIDC endpoints.

Either way, it shouldn't take a lot of code to find out :)
