### ISSUE TITLE
Legacy Password Policy Error

### ISSUE THREAD

**Issue by SamBugler** [daniel-frak/keycloak-user-migration#32]
First of all, great plugin! Works very well in general and really helps smooth over the migration.

However, I noticed that if you have a password policy in place, if a password from the legacy system doesn't meet that criteria, it throws an error. The user is created but without a password and without the ability to update their password, so effectively locked out.

It would be great to allow the legacy password to bypass the password policy since its updated straight away anyway.

Keycloak version: 12.0.4

**Comment by daniel-frak** [comment]
Hmm, that's an interesting problem that should definitely be fixed!

Would you like to create a PR for this?

**Comment by mrugesh-roambee** [comment]
@daniel-frak is it fixed? I am stuck here, because I don't want to let my users know that their auth strategy got changed, I want them to use the exact same password in keycloak, NOTE: I keep encrypted passwords. And I can dycrypt to before sending it to keycloak.

**Comment by daniel-frak** [comment]
The problem with encrypted passwords that you can decrypt is that they're not really encrypted in a safe way - you should definitely not be doing that and it's a bit of a breach of trust between you and your users if you do.

That said, I haven't really had time to implement a fix for this, nor has anyone come forward with a Pull Request yet :(

**Comment by mrugesh-roambee** [comment]
> The problem with encrypted passwords that you can decrypt is that they're not really encrypted in a safe way - you should definitely not be doing that and it's a bit of a breach of trust between you and your users if you do.
> 
> That said, I haven't really had time to implement a fix for this, nor has anyone come forward with a Pull Request yet :(

That is true, we'll be updating that soon. How should we migrate all existing users to keycloak without being noticed?

**Comment by daniel-frak** [comment]
Just going out on a limb here since I've never been in a situation like that, but since you already have full access to the users' passwords, maybe it would be easiest to write a script that writes data directly to the Keycloak database?
All you'd have to do is replicate how Keycloak encrypts the passwords and you could migrate all of the users pretty much instantly.

**Comment by daniel-frak** [comment]
This should be technically possible, though perhaps not advisable, as the user might log out before changing his password and that would lock him out as well, I believe.

I haven't had the time to investigate this issue but I'm guessing the problem might be with the `LegacyProvider::updateCredential` method being called at the wrong time, severing the federation link to the legacy system prematurely:
https://github.com/daniel-frak/keycloak-user-migration/blob/f9d51b21de3a975b0b5a5987ef3b041b77704d2e/src/main/java/com/danielfrak/code/keycloak/providers/rest/LegacyProvider.java#L107

It seems weird to me that this would happen, though, as the actual setting of credentials happens in `LegacyProvider::isValid`:
https://github.com/daniel-frak/keycloak-user-migration/blob/f9d51b21de3a975b0b5a5987ef3b041b77704d2e/src/main/java/com/danielfrak/code/keycloak/providers/rest/LegacyProvider.java#L73

I'd assume the line above would throw an exception if something's wrong with the password, thus not severing the federation link, thus not locking out the user (though perhaps I'm misunderstanding the problem).

Nevertheless, I'm confident that the answer to this problem lies somewhere within the above lines, it's just a matter of taking the time to investigate this deeper.

**Comment by sreckolipovsek** [comment]
Hi, I replace line 73:

session.userCredentialManager().updateCredential(realmModel, userModel, input);

with:

if(userModel.getRequiredActionsStream().anyMatch(s -> s.contains("UPDATE_PASSWORD")))     		
        		session.userCredentialManager().updateCredential(realmModel, userModel, UserCredentialModel.password(java.util.UUID.randomUUID().toString() + "1aA!"));
        	else	
        		session.userCredentialManager().updateCredential(realmModel, userModel, input);


and it works.

**Comment by daniel-frak** [comment]
I couldn't find anything against using the `keycloak-server-spi-private`, so even though it seems fishy, I decided to include it in the POM. This gives us access to `PasswordPolicyManagerProvider`.

I've modified the code `LegacyProvider` code so that a password policy check will be done before trying to update the password (and thus also severing the federation link). If the password does not pass the policy check, the user will instead be asked to provide a new password via the `UPDATE_PASSWORD` action. The `updateCredential` method (and thus severing the federation link) should only happen once the user provides a new password, so everything should work correctly now.
